# Generates a source tarball, including depedencies, and uploads it to GitHub releases
name: release

on: push

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Make source tarball
        run: |
          set -x
          mkdir -p .cargo
          touch sdist.tar.gz
          cargo vendor --locked >> .cargo/config.toml
          version=$(cargo pkgid -p rpmoci | cut -d '#' -f 2)
          tar --transform="s+^\./+rpmoci-$version/+" --exclude='.git' --exclude='target' --exclude='sdist.tar.gz' -czvf sdist.tar.gz .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sdist.tar.gz

  rpm:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - name: Install dependencies
        run: unset HOME; tdnf install -y build-essential git openssl-devel python3-devel sudo ca-certificates dnf
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Install cargo about 
        run: cargo install cargo-about
      - name: Make rpmoci RPM
        run: make rpm
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/rpmoci*.rpm
            NOTICE
